### ISSUE TITLE
Hide window on startup

### ISSUE THREAD

**Issue by hotice** [XCMer/fuzzy-window-switcher#1]
When launching Fuzzy Window Switcher, its main window should be hidden. Without this, if the application has been added to startup, the window is visible when logging in.

**Comment by XCMer** [comment]
Actually, I hadn't finished writing this, primarily because of some window focus issues I was having. However, I'l try completing it asap now. The window shows up in the beginning primarily for debugging purposes (from the time when I didn't have the hotkey implemented). Fixes and enhancements would start rolling in shortly.

**Comment by hotice** [comment]
Great, thank you!

**Comment by XCMer** [comment]
The window is now hidden by default (and the focusing issue fixed). You also have a configuration file to specify the hotkey now. (The README details this)

**Comment by hotice** [comment]
Thanks very much for this. One issue though: the application doesn't start if the config file doesn't exist. I'll create a new bug for this.
