### ISSUE TITLE
App doesn't start if the config file doesn't exist

### ISSUE THREAD

**Issue by hotice** [XCMer/fuzzy-window-switcher#3]
Fuzzy Window Switcher doesn't start if the ~/.fuzzy-windows config file doesn't exist. Here's the output:

Traceback (most recent call last):
  File "/usr/local/bin/fuzzy-windows", line 207, in <module>
    if (type(config.get('Default', 'ignored_windows')) is str):
  File "/usr/lib/python2.7/ConfigParser.py", line 607, in get
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'Default'

**Comment by XCMer** [comment]
This has been fixed. You'll have to change one small thing in the config file (if you're using one). Change the "[Default]" to be "[DEFAULT]" instead (just a change in the case). This should now function well with or without the config file. Also, I've changed the default hotkey to be F10 (instead of F11).

**Comment by hotice** [comment]
It works now, thank you very much for the quick fix!
